/*
 * This file is generated by jOOQ.
 */
package br.hackthon.drugstore.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Drugstore implements Serializable {

    private static final long serialVersionUID = 755779382;

    private Long       idStore;
    private String     dsName;
    private String     dsAddress;
    private BigDecimal vlLatitude;
    private BigDecimal vlLongitude;

    public Drugstore() {}

    public Drugstore(Drugstore value) {
        this.idStore = value.idStore;
        this.dsName = value.dsName;
        this.dsAddress = value.dsAddress;
        this.vlLatitude = value.vlLatitude;
        this.vlLongitude = value.vlLongitude;
    }

    public Drugstore(
        Long       idStore,
        String     dsName,
        String     dsAddress,
        BigDecimal vlLatitude,
        BigDecimal vlLongitude
    ) {
        this.idStore = idStore;
        this.dsName = dsName;
        this.dsAddress = dsAddress;
        this.vlLatitude = vlLatitude;
        this.vlLongitude = vlLongitude;
    }

    public Long getIdStore() {
        return this.idStore;
    }

    public void setIdStore(Long idStore) {
        this.idStore = idStore;
    }

    public String getDsName() {
        return this.dsName;
    }

    public void setDsName(String dsName) {
        this.dsName = dsName;
    }

    public String getDsAddress() {
        return this.dsAddress;
    }

    public void setDsAddress(String dsAddress) {
        this.dsAddress = dsAddress;
    }

    public BigDecimal getVlLatitude() {
        return this.vlLatitude;
    }

    public void setVlLatitude(BigDecimal vlLatitude) {
        this.vlLatitude = vlLatitude;
    }

    public BigDecimal getVlLongitude() {
        return this.vlLongitude;
    }

    public void setVlLongitude(BigDecimal vlLongitude) {
        this.vlLongitude = vlLongitude;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Drugstore (");

        sb.append(idStore);
        sb.append(", ").append(dsName);
        sb.append(", ").append(dsAddress);
        sb.append(", ").append(vlLatitude);
        sb.append(", ").append(vlLongitude);

        sb.append(")");
        return sb.toString();
    }
}
