/*
 * This file is generated by jOOQ.
 */
package br.hackthon.account.model.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = 25811599;

    private Long       id;
    private Long       nrIdentity;
    private String     dsUsename;
    private String     dsPassword;
    private String     dsName;
    private Date       dtBirth;
    private String     dsEmail;
    private String     dsAddress;
    private BigDecimal vlLatitude;
    private BigDecimal vlLongitude;

    public Account() {}

    public Account(Account value) {
        this.id = value.id;
        this.nrIdentity = value.nrIdentity;
        this.dsUsename = value.dsUsename;
        this.dsPassword = value.dsPassword;
        this.dsName = value.dsName;
        this.dtBirth = value.dtBirth;
        this.dsEmail = value.dsEmail;
        this.dsAddress = value.dsAddress;
        this.vlLatitude = value.vlLatitude;
        this.vlLongitude = value.vlLongitude;
    }

    public Account(
        Long       id,
        Long       nrIdentity,
        String     dsUsename,
        String     dsPassword,
        String     dsName,
        Date       dtBirth,
        String     dsEmail,
        String     dsAddress,
        BigDecimal vlLatitude,
        BigDecimal vlLongitude
    ) {
        this.id = id;
        this.nrIdentity = nrIdentity;
        this.dsUsename = dsUsename;
        this.dsPassword = dsPassword;
        this.dsName = dsName;
        this.dtBirth = dtBirth;
        this.dsEmail = dsEmail;
        this.dsAddress = dsAddress;
        this.vlLatitude = vlLatitude;
        this.vlLongitude = vlLongitude;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getNrIdentity() {
        return this.nrIdentity;
    }

    public void setNrIdentity(Long nrIdentity) {
        this.nrIdentity = nrIdentity;
    }

    public String getDsUsename() {
        return this.dsUsename;
    }

    public void setDsUsename(String dsUsename) {
        this.dsUsename = dsUsename;
    }

    public String getDsPassword() {
        return this.dsPassword;
    }

    public void setDsPassword(String dsPassword) {
        this.dsPassword = dsPassword;
    }

    public String getDsName() {
        return this.dsName;
    }

    public void setDsName(String dsName) {
        this.dsName = dsName;
    }

    public Date getDtBirth() {
        return this.dtBirth;
    }

    public void setDtBirth(Date dtBirth) {
        this.dtBirth = dtBirth;
    }

    public String getDsEmail() {
        return this.dsEmail;
    }

    public void setDsEmail(String dsEmail) {
        this.dsEmail = dsEmail;
    }

    public String getDsAddress() {
        return this.dsAddress;
    }

    public void setDsAddress(String dsAddress) {
        this.dsAddress = dsAddress;
    }

    public BigDecimal getVlLatitude() {
        return this.vlLatitude;
    }

    public void setVlLatitude(BigDecimal vlLatitude) {
        this.vlLatitude = vlLatitude;
    }

    public BigDecimal getVlLongitude() {
        return this.vlLongitude;
    }

    public void setVlLongitude(BigDecimal vlLongitude) {
        this.vlLongitude = vlLongitude;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(nrIdentity);
        sb.append(", ").append(dsUsename);
        sb.append(", ").append(dsPassword);
        sb.append(", ").append(dsName);
        sb.append(", ").append(dtBirth);
        sb.append(", ").append(dsEmail);
        sb.append(", ").append(dsAddress);
        sb.append(", ").append(vlLatitude);
        sb.append(", ").append(vlLongitude);

        sb.append(")");
        return sb.toString();
    }
}
