/*
 * This file is generated by jOOQ.
 */
package br.hackthon.drugstore.jooq;


import br.hackthon.drugstore.jooq.tables.Drug;
import br.hackthon.drugstore.jooq.tables.StoreDrugs;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Drugstore extends SchemaImpl {

    private static final long serialVersionUID = -73961304;

    /**
     * The reference instance of <code>drugstore</code>
     */
    public static final Drugstore DRUGSTORE = new Drugstore();

    /**
     * The table <code>drugstore.drug</code>.
     */
    public final Drug DRUG = br.hackthon.drugstore.jooq.tables.Drug.DRUG;

    /**
     * The table <code>drugstore.drugstore</code>.
     */
    public final br.hackthon.drugstore.jooq.tables.Drugstore DRUGSTORE_ = br.hackthon.drugstore.jooq.tables.Drugstore.DRUGSTORE_;

    /**
     * The table <code>drugstore.store_drugs</code>.
     */
    public final StoreDrugs STORE_DRUGS = br.hackthon.drugstore.jooq.tables.StoreDrugs.STORE_DRUGS;

    /**
     * No further instances allowed
     */
    private Drugstore() {
        super("drugstore", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Drug.DRUG,
            br.hackthon.drugstore.jooq.tables.Drugstore.DRUGSTORE_,
            StoreDrugs.STORE_DRUGS);
    }
}
