/*
 * This file is generated by jOOQ.
 */
package br.hackthon.drugstore.jooq;


import br.hackthon.drugstore.jooq.tables.Drug;
import br.hackthon.drugstore.jooq.tables.Drugstore;
import br.hackthon.drugstore.jooq.tables.StoreDrugs;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>drugstore</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DRUG_DS_NAME = Indexes0.DRUG_DS_NAME;
    public static final Index DRUG_PRIMARY = Indexes0.DRUG_PRIMARY;
    public static final Index DRUGSTORE_DS_NAME = Indexes0.DRUGSTORE_DS_NAME;
    public static final Index DRUGSTORE_PRIMARY = Indexes0.DRUGSTORE_PRIMARY;
    public static final Index STORE_DRUGS_ID_DRUG = Indexes0.STORE_DRUGS_ID_DRUG;
    public static final Index STORE_DRUGS_ID_STORE = Indexes0.STORE_DRUGS_ID_STORE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DRUG_DS_NAME = Internal.createIndex("ds_name", Drug.DRUG, new OrderField[] { Drug.DRUG.DS_NAME }, true);
        public static Index DRUG_PRIMARY = Internal.createIndex("PRIMARY", Drug.DRUG, new OrderField[] { Drug.DRUG.ID_DRUG }, true);
        public static Index DRUGSTORE_DS_NAME = Internal.createIndex("ds_name", Drugstore.DRUGSTORE_, new OrderField[] { Drugstore.DRUGSTORE_.DS_NAME }, true);
        public static Index DRUGSTORE_PRIMARY = Internal.createIndex("PRIMARY", Drugstore.DRUGSTORE_, new OrderField[] { Drugstore.DRUGSTORE_.ID_STORE }, true);
        public static Index STORE_DRUGS_ID_DRUG = Internal.createIndex("id_drug", StoreDrugs.STORE_DRUGS, new OrderField[] { StoreDrugs.STORE_DRUGS.ID_DRUG }, false);
        public static Index STORE_DRUGS_ID_STORE = Internal.createIndex("id_store", StoreDrugs.STORE_DRUGS, new OrderField[] { StoreDrugs.STORE_DRUGS.ID_STORE }, false);
    }
}
