/*
 * This file is generated by jOOQ.
 */
package br.hackthon.drugstore.jooq;


import br.hackthon.drugstore.jooq.tables.Drug;
import br.hackthon.drugstore.jooq.tables.Drugstore;
import br.hackthon.drugstore.jooq.tables.StoreDrugs;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in drugstore
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>drugstore.drug</code>.
     */
    public static final Drug DRUG = br.hackthon.drugstore.jooq.tables.Drug.DRUG;

    /**
     * The table <code>drugstore.drugstore</code>.
     */
    public static final Drugstore DRUGSTORE_ = br.hackthon.drugstore.jooq.tables.Drugstore.DRUGSTORE_;

    /**
     * The table <code>drugstore.store_drugs</code>.
     */
    public static final StoreDrugs STORE_DRUGS = br.hackthon.drugstore.jooq.tables.StoreDrugs.STORE_DRUGS;
}
