/*
 * This file is generated by jOOQ.
 */
package br.hackthon.account.model.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account extends SchemaImpl {

    private static final long serialVersionUID = -184009618;

    /**
     * The reference instance of <code>account</code>
     */
    public static final Account ACCOUNT = new Account();

    /**
     * The table <code>account.account</code>.
     */
    public final br.hackthon.account.model.jooq.tables.Account ACCOUNT_ = br.hackthon.account.model.jooq.tables.Account.ACCOUNT_;

    /**
     * No further instances allowed
     */
    private Account() {
        super("account", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            br.hackthon.account.model.jooq.tables.Account.ACCOUNT_);
    }
}
