/*
 * This file is generated by jOOQ.
 */
package br.hackthon.account.model.jooq;


import br.hackthon.account.model.jooq.tables.Account;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>account</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNT_DS_USENAME = Indexes0.ACCOUNT_DS_USENAME;
    public static final Index ACCOUNT_NR_IDENTITY = Indexes0.ACCOUNT_NR_IDENTITY;
    public static final Index ACCOUNT_PRIMARY = Indexes0.ACCOUNT_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNT_DS_USENAME = Internal.createIndex("ds_usename", Account.ACCOUNT_, new OrderField[] { Account.ACCOUNT_.DS_USENAME }, true);
        public static Index ACCOUNT_NR_IDENTITY = Internal.createIndex("nr_identity", Account.ACCOUNT_, new OrderField[] { Account.ACCOUNT_.NR_IDENTITY }, true);
        public static Index ACCOUNT_PRIMARY = Internal.createIndex("PRIMARY", Account.ACCOUNT_, new OrderField[] { Account.ACCOUNT_.ID }, true);
    }
}
