/*
 * This file is generated by jOOQ.
 */
package br.hackthon.account.model.jooq;


import br.hackthon.account.model.jooq.tables.Account;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in account
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>account.account</code>.
     */
    public static final Account ACCOUNT_ = Account.ACCOUNT_;
}
