/*
 * This file is generated by jOOQ.
 */
package br.hackthon.drugstore.jooq.tables.records;


import br.hackthon.drugstore.jooq.tables.Drug;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrugRecord extends UpdatableRecordImpl<DrugRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 635717776;

    /**
     * Setter for <code>drugstore.drug.id_drug</code>.
     */
    public void setIdDrug(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>drugstore.drug.id_drug</code>.
     */
    public Long getIdDrug() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>drugstore.drug.ds_name</code>.
     */
    public void setDsName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>drugstore.drug.ds_name</code>.
     */
    public String getDsName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>drugstore.drug.ds_description</code>.
     */
    public void setDsDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>drugstore.drug.ds_description</code>.
     */
    public String getDsDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Drug.DRUG.ID_DRUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Drug.DRUG.DS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Drug.DRUG.DS_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdDrug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDsDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdDrug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDsDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRecord value1(Long value) {
        setIdDrug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRecord value2(String value) {
        setDsName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRecord value3(String value) {
        setDsDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrugRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DrugRecord
     */
    public DrugRecord() {
        super(Drug.DRUG);
    }

    /**
     * Create a detached, initialised DrugRecord
     */
    public DrugRecord(Long idDrug, String dsName, String dsDescription) {
        super(Drug.DRUG);

        set(0, idDrug);
        set(1, dsName);
        set(2, dsDescription);
    }
}
