/*
 * This file is generated by jOOQ.
 */
package br.hackthon.drugstore.jooq.tables.records;


import br.hackthon.drugstore.jooq.tables.StoreDrugs;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreDrugsRecord extends TableRecordImpl<StoreDrugsRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -1484167991;

    /**
     * Setter for <code>drugstore.store_drugs.id_store</code>.
     */
    public void setIdStore(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>drugstore.store_drugs.id_store</code>.
     */
    public Long getIdStore() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>drugstore.store_drugs.id_drug</code>.
     */
    public void setIdDrug(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>drugstore.store_drugs.id_drug</code>.
     */
    public Long getIdDrug() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return StoreDrugs.STORE_DRUGS.ID_STORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return StoreDrugs.STORE_DRUGS.ID_DRUG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdStore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getIdDrug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdStore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getIdDrug();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoreDrugsRecord value1(Long value) {
        setIdStore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoreDrugsRecord value2(Long value) {
        setIdDrug(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StoreDrugsRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreDrugsRecord
     */
    public StoreDrugsRecord() {
        super(StoreDrugs.STORE_DRUGS);
    }

    /**
     * Create a detached, initialised StoreDrugsRecord
     */
    public StoreDrugsRecord(Long idStore, Long idDrug) {
        super(StoreDrugs.STORE_DRUGS);

        set(0, idStore);
        set(1, idDrug);
    }
}
